title: Cyrille Kone
affiliation: Inria Scool (Lille)
email: cyrille.kone at inria dot fr
logo: /assets/img/logo.jpg
description: PhD candidate in Reinforcement Learning.
theme: jekyll-theme-minimal
google_scholar: https://scholar.google.com/
github_link: https://github.com/yaoyao-liu/minimal-light
linkedin: https://www.linkedin.com/
avatar: ./assets/img/avatar.png
google_analytics:
is_user_page: false
is_project_page: false
show_downloads: false
#favicon: ./assets/img/favicon.png
#favicon_dark: ./assets/img/favicon-dark.png
