title: Minimal theme
affiliation: Inria Scool (Lille)
email: cyrille.kone@inria.fr
logo: /assets/img/logo.png
description: PhD candidate in Reinforcement Learning <br> cyrille.kone at inria dot fr.
show_downloads: false
theme: jekyll-theme-minimal
google_scholar: https://scholar.google.com/
github_link: https://github.com/yaoyao-liu/minimal-light
linkedin: https://www.linkedin.com/
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
#favicon: ./assets/img/favicon.png
#favicon_dark: ./assets/img/favicon-dark.png