title: Cyrille Kone
affiliation: Inria Scool (ex SequeL, Lille)
email: cyrille.kone at inria dot fr
logo: /assets/img/photo.jpg
description:
theme: jekyll-theme-minimal
google_scholar: https://scholar.google.com/citations?user=V9uXWnIAAAAJ&hl=fr&citsig=ADIE8slGmUZh5I1V9_RedLcnMgnL
github_link: https://github.com/cyrille-kone/
linkedin: https://www.linkedin.com/in/cyrille-k-57b0b6194/
#avatar: ./assets/img/avatar.png
google_analytics:
is_user_page: false
is_project_page: false
show_downloads: false
#favicon: ./assets/img/favicon.png
#favicon_dark: ./assets/img/favicon-dark.png
